name: Funry Switch Gateway
version: "0.0.88"
slug: funry_switch_gateway
description: Funry Switch Gateway Home Assistant Add-On
url: "https://github.com/glowar/Funry_Switch_Gateway/blob/main/Funry_Switch_Gateway"
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
init: false
host_network: true
#startup: services
ports:
  10502/tcp: 10502
options:
  mode: "TCP1"
  listen_address: "0.0.0.0"
  listen_port: 10502
  mqtt_address: "192.168.1.121"
  mqtt_port: 1883
  mqtt_user: "mqtt"
  mqtt_password: "Aa123592"
  serial_port: "COM8"
  serial_rate: 57600
schema:
  mode: "list(Serial|TCP1|TCP2)?"
  listen_address: "str?"
  listen_port: "int?"
  mqtt_port: "int?"
  mqtt_user: "str?"
  mqtt_password: "str?"
  serial_port: "str?"
  serial_rate: "int?"
